jobs:
- job: AutoDeploy
  continueOnError: true
  steps:

  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout Shared Pipeline Steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared

  # Run Unit steps
  - template: ./Steps/apply.yml@tfpipeline-shared