jobs:
- job: Evaluate
  displayName: 'Create Plan'
  dependsOn: Plan
  condition: eq(dependencies.Plan.result,'Succeeded')
  continueOnError: false
  steps:
  
  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout Shared Pipeline Steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared

  # Run Unit steps
  - template: ./Steps/plan_auth.yml@tfpipeline-shared