jobs:
- job: Evaluate
  displayName: 'Create Plan'
  dependsOn: New
  condition: or(eq(dependencies.Import.result,'Succeeded'),eq(dependencies.Import.result,'Skipped'))
  continueOnError: false
  steps:
  
  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout Shared Pipeline Steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared
    env:
      AZDO_PERSONAL_ACCESS_TOKEN: $(github_pat)
      AZDO_ORG_SERVICE_URL: $(org_url)

  # Run Unit steps
  - template: ./Steps/plan.yml@tfpipeline-shared