jobs:
- job: ReEvaluate
  dependsOn: Delay
  continueOnError: false
  steps:
  
  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout shared Pipeline steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared

  # Run Unit steps
  - template: ./Steps/replan.yml@tfpipeline-shared