stages:
- stage: Apply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Plan
  condition: and(not(failed()), not(canceled()), eq(dependencies.Plan.outputs['Evaluate.OPAVariable.AutoApproveShouldRun'], 'true'))
  jobs:

  # Apply Jobs
  - template: ../Jobs/apply.yml